### ISSUE TITLE
span elements are included in NBG(R_i)

### ISSUE THREAD

**Issue by palemieux** [w3c/imsc-hrm#5] opened 2021-06-02 18:44 UTC
NBG(R<sub>i</sub>) counts the number of `tts:backgroundColor` attributes specified  `span` elements. 

In a common scenario illustrated below, this results in the complexity of painting (relatively small) span backgrounds to be equal to painting the background of (relatively much larger) region that essentially fills the root container.

![image](https://user-images.githubusercontent.com/4871350/135488781-64e83b94-fe74-4c7e-8cb8-5761fcc659d0.png)

This can be addressed by excluding `span` from the NBG(R<sub>i</sub>) computation, and instead including `tts:backgroundColor` in the list of glyph properties at https://www.w3.org/TR/ttml-imsc1.1/#paint-text.

**Comment by palemieux** [comment] 2021-09-26 22:47
> I'm not saying that the pointer is necessarily at the right place on the dial now; just that moving it all the way to "highly optimised" would also be a mistake.

The ratio of _the cost of drawing a background behind a span_ over _the cost of drawing a background behind the root container_ will approach 0 as the font size approaches 0, even for an _extremely naive renderer_.

**Comment by nigelmegitt** [comment] 2021-09-27 15:37
> > I'm not saying that the pointer is necessarily at the right place on the dial now; just that moving it all the way to "highly optimised" would also be a mistake.
> 
> The ratio of _the cost of drawing a background behind a span_ over _the cost of drawing a background behind the root container_ will approach 0 as the font size approaches 0, even for an _extremely naive renderer_.

I don't think that's necessarily correct.  The current _terrible case_ naive renderer model builds a map of all the backgrounds, as it progresses linearly through the content, and every time it finds a new one, redraws the whole region background. 

Anyhow, I think it's a strong point by @btsimonh that the processing requirements for a renderer mean that text layout has to happen in full before background painting can begin. Perhaps it would make sense to define the creation of a set of rectangles in different colours (and transparencies) and count the painting time of each of those, dependent on its visible area. But doing it as part of glyph painting seems problematic, for the reasons stated [earlier](https://github.com/w3c/imsc-hrm/issues/5#issuecomment-853758689).

Then we'd have:
1. Layout the text
2. Generate an ordered set of coloured rectangles from the region, body, div, p and span-generated areas.
3. Count the paint time of each _based on its size_
4. Count the glyph draw time.

**Comment by btsimonh** [comment] 2021-09-27 16:12
"Perhaps it would make sense to define the creation of a set of rectangles in different colours (and transparencies)" - this is almost exactly what I do in my renderer which I wrote some time back.
1/ layout the text.
2/ create a list of the 'boxes' required to be drawn.
3/ create a list of the 'background elements' (outline, shadow, etc) with bounding boxes/locations.
4/ create a list of the textual elements with bounding boxes/locations.
render the lists in order 2,3,4
For a render of EACH element (be it box, background, or text), don't forget it may need to read the existing pixel values to correctly blend.  e.g. the background and text elements may well end up with an image which includes pixels which have transparency.... even the boxes may be anti-aliased (50% opacity) top/bottom to reduce interlace twitter.  Non anti-aliased characters and backgrounds are just plain ugly :).
I think we can state the assumptions of the HRM - and these don't _have_ to absolutely bottom dollar...  but from the above, maybe we need to consider 3 x blend operations per 'text area' rendered? (or 3 x blend operations for the _occupied_ area of the region?)

**Comment by nigelmegitt** [comment] 2021-09-27 16:16
> it may need to read the existing pixel values to correctly blend. e.g. the background and text elements may well end up with an image which includes pixels which have transparency

+1 - I expect we'd factor this into the painting "speed"

**Comment by nigelmegitt** [comment] 2023-12-21 17:18
Discussed in TTWG meeting today, minuted at https://www.w3.org/2023/12/21-tt-minutes.html#r01 :

> Nigel: Yes, it felt like we were overestimating complexity but in practice everything has passed.
> 
> Pierre: We should keep it open but note that we are not addressing it in imsc-hrm v1.
> 
> Nigel: I think I will propose something different.
> … I think we should close on the basis that we haven't demonstrated that there's a real world problem.
> … If later someone says they have documents that they think should pass, but which don't,
> … then at that stage we should investigate and open an issue based on the investigation, and there's
> … a chance it could be this cause, so we could reopen or open a new issue. But right now
> … this is not a demonstrated real world problem.
> 
> Pierre: I'm fine with that.
> … We should note it as a comment, or record what we just discussed.
> 
> Nigel: We spent a lot of time on that issue, but I think it gets trumped by the implementation experience.
> 
> Gary: We could post this on the issue, wait a short while and then close if nobody objects.
> 
> Nigel: +1
> … I will add a pointer to this conversation to the issue after the meeting and propose to close it with no change.

The proposal is to **close this issue with no change** on the basis that in practice, the potential overestimate of background painting time in the HRM discussed in this issue has not caused any documents to fail validation unexpectedly.

If, in the future, implementation and usage experience shows that there are documents that are expected to pass HRM validation but actually fail, then we would analyse those cases and either open new issues or, if the cause is the same, we could reopen this issue.

I will return to this after January 8th 2024 and if there are no objections, I will close this issue.

**Closed** 2023-12-28 18:56 UTC
Labels: for review
